services:
  vulnerable:
    build: ./vulnerable
    ports:
      - "127.0.0.1:8016:5000"
    networks:
      - lab-vulnerable
  fixed:
    build: ./fixed
    ports:
      - "127.0.0.1:8116:5000"
    networks:
      - lab-fixed
  oob-listener:
    build: ./oob-listener
    networks:
      - lab-vulnerable
      - lab-fixed

networks:
  lab-vulnerable:
  lab-fixed:
